services:
  postgres:
    image: postgres:17
    container_name: automation-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: automation
      POSTGRES_PASSWORD: automation_password
      POSTGRES_DB: automation_platform

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
